server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false  #moved to bootstrap.yml. Doesn't Edgware support it in application.yml?
        git:
          uri: https://github.com/carnellj/config-repo/
          searchPaths: licensingservice,organizationservice
          username: native-cloud-apps
          password: 0ffended

#server:
#  port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///C:\Users\rhernandez\IdeaProjects\spmia-chapter2-master\confsvr\src\main\resources\config\licensingservice